name = "rollnconnect-backend"
main = "src/index.js"
compatibility_date = "2025-01-01"

# -------------------------
# D1 Database
# -------------------------
[[d1_databases]]
binding = "DB"
database_name = "rollnconnect-clips"
database_id = "<PASTE_D1_DATABASE_ID_HERE>"

# -------------------------
# R2 Bucket
# -------------------------
[[r2_buckets]]
binding = "MEDIA_BUCKET"
bucket_name = "<PASTE_R2_BUCKET_NAME_HERE>"

# -------------------------
# KV Namespace
# -------------------------
[[kv_namespaces]]
binding = "KV"
id = "94027daf38234d6a914cfd48c91e55f3"
preview_id = "<ID_OF_PREVIEW_KV_NAMESPACE_FOR_LOCAL_DEVELOPMENT>"

# -------------------------
# Environment Variables
# -------------------------
[vars]
ENVIRONMENT = "production"
