name = "rollnconnect"
main = "src/index.js"
compatibility_date = "2024-01-01"
account_id = "cd66209393471bee4b76a0f267205f55"

[[kv_namespaces]]
binding = "CONNECT_KV"
id = "94027daf38234d6a914cfd48c91e55f3"

[[kv_namespaces]]
binding = "NOTIFICATIONS_KV"
id = "877e41ef396945febb7e2057886d7fcc"

[[d1_databases]]
binding = "DB"
database_name = "rollyconnect"
database_id = "51b47666-6993-4aaa-9205-c001a42a6bf6"
